name: Android Release Workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

  workflow_call:
  workflow_dispatch:
#    inputs:
#      releaseToGooglePlay:
#        description: 'Release to Google Play?'
#        required: true
#        default: 'false'

jobs:
  aab:
    name: Generate AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 21

      - name: Get tag name
        id: get_tag_name
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build Artifacts
        id: buildApks
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: android:bundle

      - uses: kevin-david/zipalign-sign-android-release@v2.0.1
        name: Sign app APK
        id: fiveofakind_sign
        with:
          releaseDirectory: android/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        run: |
          cp ${{ steps.fiveofakind_sign.outputs.signedReleaseFile }} fiveofakind-release.aab

      - uses: actions/upload-artifact@v4
        with:
          name: Signed fiveofakind App
          path: fiveofakind-release.aab

  apk:
    name: Generate Apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 21

      - name: Get tag name
        id: get_tag_name
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build Artifacts
        id: buildApks
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: android:assembleRelease

      - uses: kevin-david/zipalign-sign-android-release@v2.0.1
        name: Sign app APK
        id: fiveofakind_apk_sign
        with:
          releaseDirectory: android/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Clean up build artifacts
        run: |
          cp ${{ steps.fiveofakind_apk_sign.outputs.signedReleaseFile }} fiveofakind-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Signed fiveofakind Apk
          path: fiveofakind-release.apk
